# Generated by Django 3.1.3 on 2020-11-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fotoğraf',
            new_name='image',
        ),
    ]
