# Generated by Django 3.1.3 on 2020-11-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201115_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='fotoğraf',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='kullanıcı',
        ),
    ]
