# Generated by Django 3.1.3 on 2020-11-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201115_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fotoğraf',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='kullanıcı',
            new_name='user',
        ),
    ]
